### PR TITLE
Update readme with more info

### PR DESCRIPTION
**Pull request by FunkeCoder23**
add info about installing docker

update DMM setup with correct path for env

reorder env setup and DMM setup

add info about pgloader and add SQL command into a docker exec

use github markdown for notes and important info

changes docker-compose.yaml to use CONSUMER_REPLICAS var, so that all user config options are in the same place

Added information about increasing throughput (probably needs a once-over by @iPromKnight to make sure I understood the options correctly)

### CODE REVIEW

**Comment by purple-emily** [comment]
This will need checking for conflicts with #58. 

I believe there's a proposed move around of the docker compose file

**Comment by FunkeCoder23** [comment]
> This will need checking for conflicts with #58.
> 
> I believe there's a proposed move around of the docker compose file

I'll mark this as draft until that's merged, then update as necessary

**Comment by FunkeCoder23** [comment]
@Gabisonfire with #58 merged, do you want to review this?

**Comment by Gabisonfire** [comment]
Very well written, thank you!

**Pull request merged**
