### PR TITLE
Add seeders and provider back to the torrent info

### LINKED ISSUE #52: Add number of seeders on the streams page
**Is your feature request related to a problem? Please describe.**
Number of seeders  don't appear in Stremio

**Describe the solution you'd like**
Number of seeders should appear in Stremio

**Additional context**

image

### PR DESCRIPTION
**Pull request by purple-emily**
Closes #52

### CODE REVIEW

**Comment by purple-emily** [comment]
image

**Comment by iPromKnight** [comment]
The problem is atm we've no service that's updating seeders. 
So they'll only ever show what they are on the initial ingestion

It's not the responsibility of the consumer. Its sole purpose is ingestion of torrent data from the queue. We need a new separate service that handles updates of seeders periodically

Ideally this would be wrapped in pm2 in the container as it allows execution of a task on a cron schedule ala: pm2 start update-seeders.js --cron "*/15 * * * *"

**Comment by purple-emily** [comment]
Do you wish to hold this merge until thats done?

**Comment by iPromKnight** [comment]
No we can add it if you'd like 😃 
It's just they'll all say 100 as the dmm ones are hardcoded lol

**Comment by purple-emily** [comment]
So open an issue for seeder updates & link this issue?

**Comment by purple-emily** [comment]
#73 this is a good idea. Tagging the issue here for clarity.

**Comment by Gabisonfire** [comment]
Feels like this one should be closed, @purple-emily ?

**Pull request closed without merging**
